### ISSUE TITLE
Error in callback of subscribed event

### ISSUE THREAD

**Issue by rajendrap123** [polyskalov/botman-viber-driver#4]
@polyskalov 

Hello

In subscribed event callback:

`$botman->on(
    'subscribed',
    static function (array $payload, BotMan $bot) {
        $viberId = $payload['user_id'] ?? 'not yet';
        \Log::info('subscribed ' . $viberId . ' '. json_encode($payload));

        $bot->userStorage()->save([
            'viberId' => $viberId
        ]);
        // $bot->say('hi ' . $viberId,
        //         $viberId,
        //         ViberDriver::class,
        //     );

        
    }
);`

Its causing below error:

```
[2020-06-13 01:32:33] production.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/aayo.express/aayosathi/vendor/polyskalov/botman-viber-driver/src/ViberDriver.php:163)
[stacktrace]
#0 /var/www/aayo.express/aayosathi/vendor/polyskalov/botman-viber-driver/src/ViberDriver.php(163): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/aayo.express/aayosathi/vendor/botman/botman/src/BotMan.php(399): TheArdent\\Drivers\\Viber\\ViberDriver->getMessages()
#2 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): BotMan\\BotMan\\BotMan->BotMan\\BotMan\\{closure}()
#3 /var/www/aayo.express/aayosathi/vendor/botman/botman/src/BotMan.php(405): Illuminate\\Support\\Collection->each()
#4 /var/www/aayo.express/aayosathi/vendor/botman/botman/src/BotMan.php(419): BotMan\\BotMan\\BotMan->fireDriverEvents()
#5 /var/www/aayo.express/aayosathi/app/Http/Controllers/BotManController.php(18): BotMan\\BotMan\\BotMan->listen()
#6 [internal function]: App\\Http\\Controllers\\BotManController->handle()
#7 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#8 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#9 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#11 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#12 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#13 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#14 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#15 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#17 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#20 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#21 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#23 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#26 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#27 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#29 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#30 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#32 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then()
#33 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack()
#34 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute()
#35 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute()
#36 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#37 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#38 /var/www/aayo.express/aayosathi/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#39 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle()
#40 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#42 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#43 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#45 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#48 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#49 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#51 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#52 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#54 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#55 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /var/www/aayo.express/aayosathi/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 {main}
"} 


```

Can you pls look into this?

Thanks

**Comment by rajendrap123** [comment]
thanks
